[package]
name = "advent-of-code-2016"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-helpers = { path = "../aoc-helpers" }
md5 = "0.7.0"
rayon = "1.5.3"
